# Time interval between snapshots (in seconds)
# Example: Interval of 5 seconds 
# INTERVAL_SECONDS=5
INTERVAL_SECONDS=

# Stop date and time in 24-hour YYYY-MM-DD HH:MM format
# Example: 2026-Aug-31 at 2:52 PM
# END_TIME="2026-08-31 14:52"
END_TIME=

# Target root directory to store captures
# Example:
# OUTPUT_DIR="/home/pi/projects/timelapse_draft2/test"
OUTPUT_DIR=

# Capture command templates (use $FILENAME directly where output path is required)
# Example: Using pi cam command
# CAPTURE_CMD='rpicam-still -o "$FILENAME" --immediate -n'
CAPTURE_CMD=

# --- Video Rendering Settings ---
# Valid values are: true or false
# Example: Render video after capturing timelapse snapshots
# RENDER_VIDEO=true
RENDER_VIDEO=

# Remote rendering options
# Render snapshots remotely, valid values: true or false. If its true, you should fill all below REMOTE_* variables
REMOTE_RENDER=
# Remote User
REMOTE_USER=""
# Remote Host IP
REMOTE_HOST=""
# Remote host Port, usually 22
REMOTE_PORT=""
# Complete path for ssh key in local host
REMOTE_SSH_KEY=""
# Complete path on remote host where snapshots will be stored temporarily
REMOTE_WORK_DIR=""

# Temporary/local working video output path
# Example:
# VIDEO_OUTPUT="${OUTPUT_DIR}/timelapse_$(date '+%Y%m%d_%H%M%S').mp4"
VIDEO_OUTPUT=""

# Local render command (used when REMOTE_RENDER=false)
# Must use $CONCAT_LIST for input list and $VIDEO_OUTPUT for video output
# EXAMPLE: RENDER_CMD='ffmpeg -y -f concat -safe 0 -i "$CONCAT_LIST" -c:v libx264 -pix_fmt yuv420p "$VIDEO_OUTPUT"'
RENDER_CMD=''

# --- Final Video Storage Settings ---
# Enable final video relocation/transfer (true/false)
# Valid values are: true or false
# Example:
# STORAGE_VIDEO=true
STORAGE_ENABLE=

# Remote storage toggle (true = transfer/store on remote host via SSH/SCP, false = store in local directory)
# Example:
# STORAGE_REMOTE=true
STORAGE_REMOTE=

# Remote Storage Server Settings (Can be the same or different from RENDER settings)
STORAGE_REMOTE_USER=""
STORAGE_REMOTE_HOST=""
STORAGE_REMOTE_PORT=""
STORAGE_REMOTE_SSH_KEY=""
STORAGE_REMOTE_DIR=""

# Local Storage Directory (Used if STORAGE_REMOTE=false)
STORAGE_LOCAL_DIR=""
